package WebStuff;
// Generated Aug 2, 2020 10:09:34 PM by Hibernate Tools 4.3.1



/**
 * Zookeeper generated by hbm2java
 */
public class Zookeeper  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private String role;

    public Zookeeper() {
    }

	
    public Zookeeper(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public Zookeeper(String name, String password, String role) {
       this.name = name;
       this.password = password;
       this.role = role;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


